# Generated by Django 6.0 on 2026-05-27 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_stockledger_created_by'),
        ('raw_materials', '0006_alter_rawmaterialinventory_options'),
        ('vendors', '0003_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor_pr_number', models.CharField(blank=True, max_length=100)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('company_gstin', models.CharField(max_length=20)),
                ('vendor_gstin', models.CharField(max_length=20)),
                ('lead_days', models.PositiveIntegerField(default=0)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('pending_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='raw_materials.materialsource')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.warehouse')),
            ],
        ),
    ]
