# Generated by Django 6.0 on 2026-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('RECEIVED', 'Received')], default='DRAFT', max_length=30),
        ),
    ]
