# Generated by Django 6.0 on 2026-03-25 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0001_initial'),
        ('purchases', '0004_grn'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Purchase In'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_master.product')),
            ],
        ),
    ]
