# Generated by Django 6.0 on 2026-03-07 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_salesorder_created_by_salesorder_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispatched', models.PositiveIntegerField()),
                ('awb_number', models.CharField(blank=True, max_length=100)),
                ('transporter', models.CharField(blank=True, max_length=100)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.salesorderline')),
            ],
        ),
    ]
