# Generated by Django 6.0 on 2026-06-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('packing', '0006_packet_packet_number_packet_parent_packet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='quantity_dispatched',
        ),
        migrations.CreateModel(
            name='DispatchPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='dispatch.dispatch')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_entries', to='packing.packet')),
            ],
        ),
    ]
