# Generated by Django 6.0 on 2026-06-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_dispatch_quantity_dispatched_dispatchpacket'),
        ('packing', '0007_alter_packet_allocation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispatchpacket',
            unique_together={('dispatch', 'packet')},
        ),
    ]
