# Generated by Django 6.0 on 2026-06-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_dispatchpacket_unique_together'),
        ('packing', '0008_alter_inspection_inspection_date'),
        ('sales', '0005_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='sales_order_line',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatch_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='sales_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.salesorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='awb_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatch')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='sales.salesorderline')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dispatchpacket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dispatchpacket',
            name='dispatch_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='dispatch.dispatchitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dispatchpacket',
            unique_together={('dispatch_item', 'packet')},
        ),
        migrations.RemoveField(
            model_name='dispatchpacket',
            name='dispatch',
        ),
    ]
