# Generated by Django 6.0 on 2025-12-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(help_text='Unique SR Number identifying the product', max_length=100, unique=True)),
                ('product_name', models.CharField(help_text='Human readable product name', max_length=255)),
                ('category', models.CharField(help_text='Product category (button, elastic, tape, etc.)', max_length=100)),
                ('size_or_variant', models.CharField(help_text='Size or variant (e.g. 16L, 24L, 1 inch)', max_length=100)),
                ('color', models.CharField(help_text='Color of the product', max_length=50)),
                ('base_unit', models.CharField(choices=[('PCS', 'Pieces'), ('GROSS', 'Gross'), ('METER', 'Meter'), ('ROLL', 'Roll'), ('SET', 'Set')], default='GROSS', help_text='Base unit of measurement for this product', max_length=20)),
                ('units_per_base_unit', models.PositiveIntegerField(default=144, help_text='Conversion factor (e.g., 144 for 1 GROSS)')),
                ('default_units_per_packet', models.PositiveIntegerField(help_text='Suggested default packing quantity (editable during packing)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently active or discontinued')),
                ('image', models.ImageField(blank=True, help_text='Product image (stored in media storage)', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created')),
            ],
        ),
    ]
