# Generated by Django 6.0 on 2026-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
