# Generated by Django 6.0 on 2026-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0002_product_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Default GST percentage for this product', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC classification code', max_length=20),
        ),
    ]
