# Generated by Django 6.0 on 2026-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0003_product_gst_percentage_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description'),
        ),
    ]
