# Generated by Django 6.0 on 2026-05-15 17:12

import product_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (stored in media storage)', null=True, upload_to=product_master.models.Product.product_image_upload_path),
        ),
    ]
