# Generated by Django 6.0 on 2026-06-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0005_alter_product_image'),
        ('sampling', '0003_developmentsample_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='development_sample',
            field=models.ForeignKey(blank=True, help_text='Parent development sample from which this SR was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sampling.developmentsample'),
        ),
    ]
