# Generated by Django 6.0 on 2026-05-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_rawmaterial_minimum_quantity_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('vendor_material_code', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_sources', to='raw_materials.rawmaterial')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_sources', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('raw_material', 'vendor')},
            },
        ),
    ]
