# Generated by Django 6.0 on 2026-05-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('raw_materials', '0003_materialsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('available_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='raw_materials.materialsource')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_inventory', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'material_source')},
            },
        ),
    ]
