# Generated by Django 6.0 on 2026-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0004_rawmaterialinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='chemical_identity',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
