# Generated by Django 6.0 on 2026-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0005_rawmaterial_chemical_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialinventory',
            options={'verbose_name_plural': 'Raw Material Inventories'},
        ),
    ]
