# Generated by Django 6.0 on 2026-05-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('development_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BUTTON', 'Button'), ('TAPE', 'Tape'), ('LABEL', 'Label'), ('TAG', 'Tag'), ('OTHER', 'Other')], max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size_or_variant', models.CharField(blank=True, max_length=100)),
                ('thickness', models.CharField(blank=True, max_length=100)),
                ('finish_type', models.CharField(blank=True, max_length=100)),
                ('texture', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
