# Generated by Django 6.0 on 2026-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentsample',
            name='development_name',
        ),
        migrations.RemoveField(
            model_name='developmentsample',
            name='finish_type',
        ),
        migrations.RemoveField(
            model_name='developmentsample',
            name='texture',
        ),
        migrations.RemoveField(
            model_name='developmentsample',
            name='thickness',
        ),
        migrations.AddField(
            model_name='developmentsample',
            name='base_unit',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('GROSS', 'Gross'), ('METER', 'Meter'), ('ROLL', 'Roll'), ('SET', 'Set')], default='GROSS', help_text='Base unit', max_length=20),
        ),
        migrations.AddField(
            model_name='developmentsample',
            name='description',
            field=models.TextField(blank=True, help_text='Development notes/details'),
        ),
        migrations.AddField(
            model_name='developmentsample',
            name='mid_code',
            field=models.CharField(default='BTN', help_text='Category sequence code (e.g. BTN, LBL, TPE)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentsample',
            name='product_name',
            field=models.CharField(default='Button-pearl', help_text='Development product name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentsample',
            name='units_per_base_unit',
            field=models.PositiveIntegerField(default=144, help_text='Conversion factor (e.g. 144 for gross)'),
        ),
        migrations.AlterField(
            model_name='developmentsample',
            name='category',
            field=models.CharField(help_text='Product category (button, tape, label, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='developmentsample',
            name='color',
            field=models.CharField(help_text='Development color', max_length=50),
        ),
        migrations.AlterField(
            model_name='developmentsample',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Used when customer does not yet exist in master', max_length=255),
        ),
        migrations.AlterField(
            model_name='developmentsample',
            name='reference_code',
            field=models.CharField(help_text='Generated development reference code (e.g. VRT-BTN-001)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='developmentsample',
            name='size_or_variant',
            field=models.CharField(help_text='Variant / size (e.g. 18L-4H)', max_length=100),
        ),
    ]
