# Generated by Django 6.0 on 2026-03-07 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packing', '0001_initial'),
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('SURPLUS_IN', 'Surplus In'), ('STOCK_OUT', 'Stock Out'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_master.product')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedStockPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_in_packet', models.PositiveIntegerField()),
                ('added_to_stock_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('CONSUMED', 'Consumed')], default='IN_STOCK', max_length=20)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='packing.packet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_master.product')),
            ],
        ),
    ]
