# Generated by Django 6.0 on 2026-06-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_stock', '0001_initial'),
        ('packing', '0006_packet_packet_number_packet_parent_packet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedstockpacket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='finishedstockpacket',
            name='units_in_packet',
        ),
        migrations.AlterField(
            model_name='finishedstockpacket',
            name='packet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry', to='packing.packet'),
        ),
    ]
