# Generated by Django 6.0 on 2026-04-03 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('STATUS_CHANGE', 'Status Change'), ('APPROVE', 'Approve'), ('CANCEL', 'Cancel')], max_length=30)),
                ('module', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module'], name='activity_lo_module_53b73d_idx'), models.Index(fields=['reference_id'], name='activity_lo_referen_d4b350_idx'), models.Index(fields=['timestamp'], name='activity_lo_timesta_34d677_idx')],
            },
        ),
    ]
