# Generated by Django 6.0 on 2026-02-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(help_text='4-digit business identifier for the customer', max_length=4, unique=True)),
                ('name', models.CharField(help_text='Customer name (may repeat)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the customer is active or inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the customer was registered in the system')),
                ('billing_address', models.TextField(help_text='Billing address used for invoices')),
                ('billing_gst_number', models.CharField(blank=True, help_text='GST number for billing address (if applicable)', max_length=15, null=True)),
                ('shipping_address', models.TextField(help_text='Shipping address used for dispatch')),
                ('shipping_gst_number', models.CharField(blank=True, help_text='GST number for shipping address (if applicable)', max_length=15, null=True)),
                ('contact_numbers', models.JSONField(blank=True, default=list, help_text='List of contact phone numbers')),
                ('contact_emails', models.JSONField(blank=True, default=list, help_text='List of contact email addresses')),
                ('credit_terms', models.CharField(blank=True, help_text='Default credit terms (e.g., Advance, 30 days)', max_length=100)),
            ],
        ),
    ]
