# Generated by Django 6.0 on 2026-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='CUSTTEMP', help_text='Unique business identifier for the customer', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
