# Generated by Django 6.0 on 2026-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_vendor_id_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Karnataka', help_text='Customer state for GST determination', max_length=100),
            preserve_default=False,
        ),
    ]
