# Generated by Django 6.0 on 2026-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('DISTRIBUTOR', 'Distributor'), ('OEM', 'OEM'), ('EXPORT', 'Export'), ('INSTITUTIONAL', 'Institutional')], help_text='Customer classification', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Customer PAN number', max_length=10),
        ),
    ]
