# Generated by Django 6.0 on 2026-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_customer_type_customer_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('DISTRIBUTOR', 'Distributor'), ('OEM', 'OEM'), ('EXPORT', 'Export'), ('INSTITUTIONAL', 'Institutional'), ('OTHERS', 'Others')], help_text='Customer classification', max_length=50),
        ),
    ]
