# Generated by Django 6.0 on 2026-05-23 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0005_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=150, unique=True)),
                ('warehouse_code', models.CharField(max_length=30, unique=True)),
                ('warehouse_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOOD', 'Finished Good')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_IN', 'Purchase In'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('PRODUCTION_OUTPUT', 'Production Output'), ('PACKING_OUTPUT', 'Packing Output'), ('SALES_DISPATCH', 'Sales Dispatch'), ('MANUAL_RECEIPT', 'Manual Receipt'), ('MANUAL_ISSUE', 'Manual Issue'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('SCRAP', 'Scrap'), ('SAMPLE_USAGE', 'Sample Usage')], max_length=50)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='product_master.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('available_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='product_master.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
