# Generated by Django 6.0 on 2026-05-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('raw_materials', '0005_rawmaterial_chemical_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockledger',
            name='product',
        ),
        migrations.AddField(
            model_name='stockledger',
            name='material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='raw_materials.materialsource'),
        ),
        migrations.DeleteModel(
            name='InventoryStock',
        ),
    ]
