# Generated by Django 6.0 on 2026-05-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockledger_product_and_more'),
        ('raw_materials', '0005_rawmaterial_chemical_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='material_source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='raw_materials.materialsource'),
        ),
    ]
