# Generated by Django 6.0 on 2026-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockledger_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_IN', 'Purchase In'), ('GRN_REVERSAL', 'GRN Reversal'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('PRODUCTION_OUTPUT', 'Production Output'), ('PACKING_OUTPUT', 'Packing Output'), ('SALES_DISPATCH', 'Sales Dispatch'), ('MANUAL_RECEIPT', 'Manual Receipt'), ('MANUAL_ISSUE', 'Manual Issue'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('SCRAP', 'Scrap'), ('SAMPLE_USAGE', 'Sample Usage')], max_length=50),
        ),
    ]
