# Generated by Django 6.0 on 2026-02-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='sr_number',
        ),
    ]
