# Generated by Django 6.0 on 2026-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_created_by_salesorder_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_lead_days',
            field=models.PositiveIntegerField(default=0, help_text='Promised delivery lead time in days'),
        ),
    ]
