# Generated by Django 6.0 on 2026-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_delivery_lead_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='salesordereditlog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='sr_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_po_id',
            field=models.IntegerField(blank=True, help_text='Reference to customer purchase order', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_lead_days',
            field=models.PositiveIntegerField(blank=True, help_text='Promised delivery lead time in days', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('QC_PENDING', 'QC Pending'), ('READY_TO_DISPATCH', 'Ready To Dispatch'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
