# Generated by Django 6.0 on 2026-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnline',
            old_name='quantity',
            new_name='received_quantity',
        ),
        migrations.AddField(
            model_name='grn',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grn',
            name='received_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='grnline',
            name='line_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='received_unit',
            field=models.CharField(default='KG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grnline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='grnline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
