# Generated by Django 6.0 on 2026-06-04 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_rename_quantity_grnline_received_quantity_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnline',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchases.purchaseorder'),
        ),
    ]
