# Generated by Django 6.0 on 2026-06-04 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0003_grnline_purchase_order'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnline',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='grn',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchases.purchaseorder'),
        ),
    ]
