# Generated by Django 6.0 on 2026-03-07 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
        ('production', '0001_initial'),
        ('sales', '0003_salesorder_created_by_salesorder_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_quantity', models.PositiveIntegerField()),
                ('rejected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_in_packet', models.PositiveIntegerField()),
                ('manufacture_date', models.DateField(default=django.utils.timezone.now)),
                ('batch_number', models.CharField(max_length=30)),
                ('allocation_type', models.CharField(choices=[('ORDER', 'Order'), ('STOCK', 'Stock')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='packing.inspection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_master.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorderline')),
            ],
        ),
    ]
