# Generated by Django 6.0 on 2026-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_STOCK', 'In Stock'), ('DISPATCHED', 'Dispatched')], default='AVAILABLE', max_length=20),
        ),
    ]
