# Generated by Django 6.0 on 2026-06-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_packet_status'),
        ('production', '0005_jobcardmaterial_productionbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='production',
        ),
        migrations.AddField(
            model_name='inspection',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.productionbatch'),
        ),
    ]
