# Generated by Django 6.0 on 2026-06-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_remove_inspection_production_inspection_batch'),
        ('production', '0005_jobcardmaterial_productionbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='production',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.productionbatch'),
        ),
    ]
