# Generated by Django 6.0 on 2026-06-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_remove_packet_product_inspection_inspected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='packet_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='parent_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reallocated_packets', to='packing.packet'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='allocation_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('PROJECTION', 'Projection'), ('STOCK', 'Stock')], max_length=10),
        ),
    ]
