# Generated by Django 6.0 on 2026-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_packet_packet_number_packet_parent_packet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='allocation_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('PROJECTION', 'Projection'), ('STOCK', 'Stock')], max_length=20),
        ),
    ]
