# Generated by Django 6.0 on 2026-06-24 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_alter_packet_allocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
