# Generated by Django 6.0 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_alter_inspection_inspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
