# Generated by Django 6.0 on 2026-06-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='production_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='production.productionrequest'),
        ),
    ]
