# Generated by Django 6.0 on 2026-06-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_production_job_card_number_and_more'),
        ('raw_materials', '0006_alter_rawmaterialinventory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('issued_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_materials.materialsource')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=30, unique=True)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.production')),
            ],
        ),
    ]
