# Generated by Django 6.0 on 2026-06-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_jobcardmaterial_productionbatch'),
        ('raw_materials', '0006_alter_rawmaterialinventory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='production',
            name='primary_material_quantity',
        ),
        migrations.RemoveField(
            model_name='production',
            name='sales_order_line',
        ),
        migrations.AddField(
            model_name='jobcardmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_materials.rawmaterial'),
        ),
        migrations.AddField(
            model_name='jobcardmaterial',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcardmaterial',
            name='material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_materials.materialsource'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='production.productionrequest'),
        ),
    ]
