# Generated by Django 6.0 on 2026-06-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productionbatch_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='sr_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
