# Generated by Django 6.0 on 2026-06-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0006_product_development_sample'),
        ('production', '0008_productionrequest_sr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='production_requests', to='product_master.product'),
            preserve_default=False,
        ),
    ]
