# Generated by Django 6.0 on 2026-06-18 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_productionrequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
