# Generated by Django 6.0 on 2026-07-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_production_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('PRODUCTION_COMPLETE', 'Production Complete'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
    ]
