# Generated by Django 6.0 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_productionbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('PRODUCTION_COMPLETE', 'Production_Complete'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
