# Generated by Django 6.0 on 2026-05-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('recipes', '0001_initial'),
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='development_sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='sampling.developmentsample'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_materials.rawmaterial'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='recipes.recipe'),
        ),
    ]
